//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Community.PowerToys.CmdPal.Plugin.TOTP.Localization {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Community.PowerToys.CmdPal.Plugin.TOTP.Localization.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Add {0} authenticators 的本地化字符串。
        /// </summary>
        internal static string add_from_ga {
            get {
                return ResourceManager.GetString("add_from_ga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 From Google Authenticator App, batch {0} / {1} 的本地化字符串。
        /// </summary>
        internal static string add_from_ga_tip {
            get {
                return ResourceManager.GetString("add_from_ga_tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add new authenticator 的本地化字符串。
        /// </summary>
        internal static string add_from_otpauth_tip {
            get {
                return ResourceManager.GetString("add_from_otpauth_tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import authenticators from PowerToys Run TOTP 的本地化字符串。
        /// </summary>
        internal static string add_from_ptrun_totp {
            get {
                return ResourceManager.GetString("add_from_ptrun_totp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy 的本地化字符串。
        /// </summary>
        internal static string copy_to_cilpboard_command {
            get {
                return ResourceManager.GetString("copy_to_cilpboard_command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expired in {0}s 的本地化字符串。
        /// </summary>
        internal static string expired_in {
            get {
                return ResourceManager.GetString("expired_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exported at {0}. 的本地化字符串。
        /// </summary>
        internal static string export_done_tip {
            get {
                return ResourceManager.GetString("export_done_tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Authenticators exported 的本地化字符串。
        /// </summary>
        internal static string export_done_title {
            get {
                return ResourceManager.GetString("export_done_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export all authenticator to file for futher import. 的本地化字符串。
        /// </summary>
        internal static string export_tip {
            get {
                return ResourceManager.GetString("export_tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export authenticators 的本地化字符串。
        /// </summary>
        internal static string export_title {
            get {
                return ResourceManager.GetString("export_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import 的本地化字符串。
        /// </summary>
        internal static string import_command {
            get {
                return ResourceManager.GetString("import_command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} authenticators has been imported. 的本地化字符串。
        /// </summary>
        internal static string import_done_tip {
            get {
                return ResourceManager.GetString("import_done_tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Authenticators imported 的本地化字符串。
        /// </summary>
        internal static string import_done_title {
            get {
                return ResourceManager.GetString("import_done_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This file is not compatible with current version of plugin, try import with the version of plugin that exported this file. 的本地化字符串。
        /// </summary>
        internal static string import_failed_tip {
            get {
                return ResourceManager.GetString("import_failed_tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import failed 的本地化字符串。
        /// </summary>
        internal static string import_failed_title {
            get {
                return ResourceManager.GetString("import_failed_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import from links 的本地化字符串。
        /// </summary>
        internal static string import_from_link {
            get {
                return ResourceManager.GetString("import_from_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Paste to search bar to import, support otpauth:// and otpauth-migration:// (Google Authenticator export link) 的本地化字符串。
        /// </summary>
        internal static string import_from_link_tip {
            get {
                return ResourceManager.GetString("import_from_link_tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import authenticators from exported file. 的本地化字符串。
        /// </summary>
        internal static string import_tip {
            get {
                return ResourceManager.GetString("import_tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import authenticators 的本地化字符串。
        /// </summary>
        internal static string import_title {
            get {
                return ResourceManager.GetString("import_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid otpauth-migration link 的本地化字符串。
        /// </summary>
        internal static string invalid_ga_import_link {
            get {
                return ResourceManager.GetString("invalid_ga_import_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Try to scan QRCode and copy it again 的本地化字符串。
        /// </summary>
        internal static string invalid_ga_import_link_tip {
            get {
                return ResourceManager.GetString("invalid_ga_import_link_tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid otpauth link 的本地化字符串。
        /// </summary>
        internal static string invalid_otpauth_link {
            get {
                return ResourceManager.GetString("invalid_otpauth_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Try to scan QRCode and copy it again 的本地化字符串。
        /// </summary>
        internal static string invalid_otpauth_link_tip {
            get {
                return ResourceManager.GetString("invalid_otpauth_link_tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid authenticator 的本地化字符串。
        /// </summary>
        internal static string invalid_secret {
            get {
                return ResourceManager.GetString("invalid_secret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This authenticator contains a invalid secret that can&apos;t be decode as base32 data 的本地化字符串。
        /// </summary>
        internal static string invalid_secret_tip {
            get {
                return ResourceManager.GetString("invalid_secret_tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import first authenticator 的本地化字符串。
        /// </summary>
        internal static string no_authenticator {
            get {
                return ResourceManager.GetString("no_authenticator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import new authenticators from QRCode on screen, setup link or PowerToys Run. 的本地化字符串。
        /// </summary>
        internal static string no_authenticator_tip {
            get {
                return ResourceManager.GetString("no_authenticator_tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add new authenticators 的本地化字符串。
        /// </summary>
        internal static string page_import_name {
            get {
                return ResourceManager.GetString("page_import_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Authenticators 的本地化字符串。
        /// </summary>
        internal static string page_totp_name {
            get {
                return ResourceManager.GetString("page_totp_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy Time-based one time password to clipboard 的本地化字符串。
        /// </summary>
        internal static string plugin_description {
            get {
                return ResourceManager.GetString("plugin_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TOTP 的本地化字符串。
        /// </summary>
        internal static string plugin_name {
            get {
                return ResourceManager.GetString("plugin_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scan QR code on screen 的本地化字符串。
        /// </summary>
        internal static string scan_from_screen {
            get {
                return ResourceManager.GetString("scan_from_screen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The authenticator {0} has been imported. 的本地化字符串。
        /// </summary>
        internal static string scan_from_screen_done_one {
            get {
                return ResourceManager.GetString("scan_from_screen_done_one", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import Done 的本地化字符串。
        /// </summary>
        internal static string scan_from_screen_done_title {
            get {
                return ResourceManager.GetString("scan_from_screen_done_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} Authenticators has been imported. 的本地化字符串。
        /// </summary>
        internal static string scan_from_screen_done_two_more {
            get {
                return ResourceManager.GetString("scan_from_screen_done_two_more", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Screen doesn&apos;t contain any QR code that can be imported. 的本地化字符串。
        /// </summary>
        internal static string scan_from_screen_empty {
            get {
                return ResourceManager.GetString("scan_from_screen_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Supports standard OTP QR code 的本地化字符串。
        /// </summary>
        internal static string scan_from_screen_tip {
            get {
                return ResourceManager.GetString("scan_from_screen_tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        internal static string totp_delete_confirm {
            get {
                return ResourceManager.GetString("totp_delete_confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete {0}? Please make sure you have disable 2FA verify on the website, otherwise you will be no longer able to access your account. 的本地化字符串。
        /// </summary>
        internal static string totp_delete_description {
            get {
                return ResourceManager.GetString("totp_delete_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Authenticator {0} has been deleted. 的本地化字符串。
        /// </summary>
        internal static string totp_delete_done {
            get {
                return ResourceManager.GetString("totp_delete_done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete authenticator 的本地化字符串。
        /// </summary>
        internal static string totp_delete_title {
            get {
                return ResourceManager.GetString("totp_delete_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rename 的本地化字符串。
        /// </summary>
        internal static string totp_rename_confirm {
            get {
                return ResourceManager.GetString("totp_rename_confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rename {0} to: 的本地化字符串。
        /// </summary>
        internal static string totp_rename_description {
            get {
                return ResourceManager.GetString("totp_rename_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rename authenticator 的本地化字符串。
        /// </summary>
        internal static string totp_rename_title {
            get {
                return ResourceManager.GetString("totp_rename_title", resourceCulture);
            }
        }
    }
}
