name: Build for CmdPal
on:
  push:
    branches: [ "main" ]
    paths:
      - Zapic.PowerToys.TOTP.Core/**/*
      - Community.PowerToys.CmdPal.Plugin.TOTP/**/*
      - .github/workflows/CmdPal.yml
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v6

    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 9.0.x
    - uses: GuillaumeFalourd/setup-windows10-sdk-action@v2.4
      with:
        sdk-version: 22621

    - name: Build
      run: powershell.exe -noprofile -executionpolicy bypass .\Community.PowerToys.CmdPal.Plugin.TOTP\Scripts\build-msixbundle.ps1 -sideload -debug
    - name: Upload msixbundle
      uses: actions/upload-artifact@v7.0.0
      with:
        name: TOTP-${{ github.sha }}
        path: Community.PowerToys.CmdPal.Plugin.TOTP/AppPackages/*.msixbundle
        if-no-files-found: error
        archive: false